#!/bin/bash
#
# koorik
#
echo -n "Sisesta soovitud täisarv "
read arv
# arvutan jäägiga jagamisel
jaak=$(( $arv % 2 ))

if [ $jaak -eq 0 ]
then
   echo "$arv on paaris"
else
   echo "$arv on paaritu"
fi
#
