#! /bin/bash
#
# kasutaja tervitus
#
# echo "Tere User!"
echo -n "Tere "
echo -n `whoami | cut -c1 | tr [:lower:] [:upper:]` # lõika esimene täht ja muuda suureks
echo -n `whoami | cut -c2-` # lõika kõik tähed alates 2-st
echo "!"
#
# skripti lõpp
