#!/bin/bash
#
echo -n "Sisesta oma aluskandiku pikkus(cm): "
read pikkus
echo -n "Sisesta oma aluskandiku laius(cm): "
read laius 
echo -n "Sisesta soovitud küpsiste suurus(cm): "
read k_pikkus
echo -n "Sisesta soovitud küpsiste laius(cm): "
read k_laius
echo -n "Sisesta soovitud kihtide arv tordil(numbrites): "
read arv
echo -n "Sisesta mitu küpsist on igas pakis(numbrites): "
read pakis

#

kandik=`expr $pikkus \* $laius`
kypsis=`expr $k_pikkus \* $k_laius`
yhes_kihis=`expr $kandik / $kypsis`
kypsised=`expr $yhes_kihis \* $arv`
pakkide_arv=`expr $kypsised / $pakis`

echo "Kokku on vaja $pakkide_arv küpsise pakki"
