#!/bin/bash
#
#Kujund mida kasutaja ise saab koostada
echo -n "Sisesta tärnide arv: "
read tarv
for (( i = 1; i <= 5; i++ ))
do
if (( $i == 1 || $i == 5))
then
echo -n $i"."
	for (( j = 1; j <= $tarv; j++ ))
	do
		echo -n "*"
	done
	echo ""
else
echo -n $i". "
echo -n "*"
	for (( q = 2; q <= 4; q++ ))
	do
	echo -n " "
	done
echo "*"
fi

done
